#!/usr/bin/env bash

# Copyright 2020 Jason Bakos, Philip Conrad, Charles Daniels

# This script is installed along with the C shared libraries for WaveGen , and can
# be used by other scripts to determine the cflags and libs for the WaveGen
# library.

set -e

usage () {
	echo "$0 [--cflags] [--libs]" 1>&2
}

if [ $# -ne 1 ] ; then
	usage
	exit 1
fi

if [ $1 = "--cflags" ] ; then
	cd "$(dirname "$0")/../include/wavegen"
	printf " -I%s " "$(pwd)"
	exit 0
fi

if [ $1 = "--libs" ] ; then
	cd "$(dirname "$0")/../lib"
	printf " -L%s -lwavegen" "$(pwd)"
	exit $?
fi

usage
exit 1
